### PR TITLE
WebGL Support for Unity Apps

### PR DESCRIPTION
**Pull request by Claytonious**
Support for WebGL.

[Demo](http://www.youtube.com/watch?v=EQOTzTht2n4)

### CODE REVIEW

**Comment by avram** [comment]
@benmarten This is a PR on top of #12, so its own changes are quite small, just 2b54ca5 and 
3c6a510.

**Comment by benmarten** [comment]
Thanks, now since we merged #12. It seems there are some merge conflicts...
Maybe its worth to reopen a new PR, and do:
```
git pull
git checkout develop
git cherry-pick 2b54ca5
git cherry-pick 3c6a510
```

**Comment by avram** [comment]
Replaced by #15.

**Comment by avram** [comment]
@Claytonious can you close this PR as it is superseded by #15?

**Pull request closed without merging**
