### PR TITLE
implemented unity-jar-resolver

### PR DESCRIPTION
**Pull request by AlmirKadric**
implemented unity-jar-resolver dependencies.xml file for easy plugin resolving
this also removes the need to overload the default unity maintemplate.gradle file

### CODE REVIEW

**Comment by milos1290** [comment]
If we add support for unity-jar-resolver does it removes need to bundle play-services with unitypackage ? In my testing it seems that it will automatically pull proper aars when using it with dependencies.xml ?

**Comment by AlmirKadric** [comment]
`unity-jar-resolver` and `play-services-resolver` from my understanding are the same thing. It was just renamed at some point (https://github.com/googlesamples/unity-jar-resolver).

This being said the Unity project in question will need to have the Unity `play-services-resolver` plugin installed within their project. However I would say that is outside the scope of the Leanplum SDK.

Instead with my suggested PR, a user will have the option to use that plugin (especially if they are already using it) with the Leanplum SDK. And by doing so, yes, it will automatically pull in the correct AARs and resolve any dependency issues. Its quite a nice system. Also it doesn't overwrite the default build behavior of Unity which tends to get messy when updating to later versions of Unity.

**Comment by milos1290** [comment]
I've added unity-jar-resolver package into our Unity package, it works really great as it removes the overhead of bundling dependencies, with it we just provide our wrapper and user can choose whether to include any additional libraries through dependencies.xml. Using just dependencies.xml without unity-jar-resolver requires to keep it like it is with bundling play services, but i've noticed that in this case if users are using unity-jar-resolver they will get multiple libraries bundled within exported android project and failing to build, one coming from our unitypackage and others that will be pulled through unity-jar-resolver.

**Comment by milos1290** [comment]
merged with https://github.com/Leanplum/Leanplum-Unity-SDK/pull/45

**Pull request closed without merging**
