### PR TITLE
WebGL support

### PR DESCRIPTION
**Pull request by avram**
Adding WebGL support; replaces #14 

Demo here: https://www.youtube.com/watch?v=EQOTzTht2n4

### CODE REVIEW

**Comment by avram** [comment]
@benmarten The `#IFDEF` on so many files isn't an uncommon solution, although I freely admit that it isn't the most attractive way of doing this.

**Comment by benmarten** [comment]
Let's keep this open for another day, to give others the option to comment. Then I'll merge it and send a build to our QA team...

**Comment by insanetheta** [comment]
Awesome!  I added WebGL support to our app a few months ago, but having it in the leanplum SDK itself is much better!  Is it just for variables?

**Comment by benmarten** [comment]
I've been trying to run this in chrome locally, using: `./Google\ Chrome  --allow-file-access-from-files`

I'm seeing this error in the console...
```
PlayerConnection initialized from  (debug = 0)

blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554 PlayerConnection disabled  - listening mode not supported

blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554 Initialize engine version: 2017.1.0f3 (472613c02cf7)

UnityLoader.js:234 Creating WebGL 2.0 context.
blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554 Renderer: WebKit WebGL

blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554 Vendor:   WebKit

blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554 Version:  OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium))

blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554 GLES:     3

blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554  EXT_color_buffer_float GL_EXT_color_buffer_float EXT_disjoint_timer_query_webgl2 GL_EXT_disjoint_timer_query_webgl2 EXT_texture_filter_anisotropic GL_EXT_texture_filter_anisotropic OES_texture_float_linear GL_OES_texture_float_linear WEBGL_compressed_texture_s3tc GL_WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb GL_WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info GL_WEBGL_debug_renderer_info WEBGL_debug_shaders GL_WEBGL_debug_shaders WEBGL_lose_context GL_WEBGL_lose_context

blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554 OPENGL LOG: Creating OpenGL ES 3.0 graphics device ; Context level  <OpenGL ES 3.0> ; Context handle 1

blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554 UnloadTime: 8.830000 ms

blob:file:///2cda5eb0-2b0e-42c2-97cf-d037960c4a35:8554 SystemException: Thread creation failed.

Rethrow as TypeInitializationException: The type initializer for 'System.Threading.Timer.Scheduler' threw an exception.

Rethrow as TypeInitializationException: The type initializer for 'System.Threading.Timer' threw an exception.

Rethrow as TypeInitializationException: The type initializer for 'LeanplumSDK.Prefs.PlayerPrefs' threw an exception.

 
(Filename: currently not available on il2cpp Line: -1)
```
Any ideas what settings are required in Unity?

**Comment by benmarten** [comment]
Actually I got it working now, by selecting Build & Run, and then opening with Chrome. No JS exceptions any more. Debugger shows events now... Thanks!

**Comment by benmarten** [comment]
FYI: I've cut a release branch and sent the release to our QA team. Our CSM team will follow up on the expected timeline of the process... Thanks for your contribution! This is very much appreciated!

**Comment by avram** [comment]
Really happy to have this in mainline!

**Comment by insanetheta** [comment]
We've been running into this same threading issue, but did not get an error in chrome.  Instead we tracked down the timer by putting in a wave of debug statements and reading into System Timer.  Since System Timer is threaded, I don't understand how this plugin is working at all.  I will try implementing a simple timer to get around this, but would love an explanation as to how this could be working.

**Comment by skimtaru** [comment]
I have also been running into the threading issue for WegGL in PlayerPrefs with flushTimer

**Pull request merged**
